2023-03-03 16:20:41,936 ERROR: Exception on /login [GET] [in /home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/routes.py", line 277, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/templates/base.html", line 54, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/templates/login.html", line 12, in block 'app_content'
    <!-- <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a> <a href="{{ url_for('staff_register') }}">Click to Register as staff!</a></p> -->
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'user' instead?
2023-03-03 16:21:01,825 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:49:28,693 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:49:31,538 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:50:08,315 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:50:10,940 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:50:35,166 ERROR: Exception on /login [POST] [in /home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/routes.py", line 304, in login
    next_page = url_for('index'+"_" + current_user.user_cat)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index_manager'. Did you mean 'index_admin' instead?
2023-03-03 16:53:30,063 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:53:38,598 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:54:11,068 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:54:14,256 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
2023-03-03 16:54:25,979 ERROR: Exception on /index_admin [GET] [in /home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/routes.py", line 52, in index_admin
    return render_template('index.html', title='Home')
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/tfjuror/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/templates/index.html", line 24, in template
    {% if current_user.user_cat!='admin'}
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2023-03-03 16:54:53,033 INFO: HMS startup [in /home/tfjuror/Desktop/Courses/DBMS/Lab/DBMS-MiniProject-2023S/app/__init__.py:52]
